# Flutter build
variables:
- group: my-variable-group
- name: isMain
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
- name: isDevelop
  value: $[eq(variables['Build.SourceBranch'], 'refs/heads/develop')]

trigger:
  batch: true
  branches:
    include:
    - '*'
    exclude:
    - master

name: $(Date:yyyyMMdd)$(BuildID)
jobs:
  - job: Android
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
    - task: Bash@3
      displayName: 'Common Task'
      inputs:
        targetType: 'inline'
        script: |
          ${{ if eq(variables['Build.SourceBranchName'], 'main') }}:
            echo "This is CI on main"
            echo "This is CI on main"  
          ${{ if ne(variables['Build.SourceBranchName'], 'main') }}:
            echo "This is CI on other" 
            echo "This is CI on other" 

    - task: Bash@3
      condition: and(succeeded(), eq(variables.isMain, 'true'))
      displayName: 'Master Branch'
      inputs:
        targetType: 'inline'
        script: |
            echo "this is Master task" 

    - task: Bash@3
      condition: and(succeeded(), eq(variables.isDevelop, 'true'))
      displayName: 'Develop Branch'    
      inputs:
        targetType: 'inline'
        script: |
            echo "This is Development"