# Flutter build
variables:
- group: my-variable-group
- name: my-passed-variable
  value: $[variables.myhello] # uses runtime expression

trigger:
- master

jobs:
  - job: Android
    timeoutInMinutes: 10
    pool:
      vmImage: 'macOS-latest'
    steps:

      - task: CopyFiles@2
        inputs:
          contents: '**/*.apk'
          targetFolder: '$(build.artifactStagingDirectory)'

      - script: echo $(myhello)
      - script: echo $(my-passed-variable) 
      - script: echo $[variables.myhello] 
      - script: echo $(variables.myhello)
      - script: echo $(my-variable-group.myhello)
      - script: echo $[my-variable-group.myhello] 

      - task: XplatGenerateReleaseNotes@3
        inputs:
          outputfile: '$(build.artifactStagingDirectory)/releasenotes.md'
          templateLocation: 'InLine'
          inlinetemplate: |
            #### Commit:{{buildDetails.sourceVersion}}
            #### Branch: {{buildDetails.sourceBranch}}
            {{#forEach commits}}
            {{#if isFirst}}### Release Notes:{{/if}}
            * {{this.message}}
            {{/forEach}}
          gitHubPat: '$(gitpattoken)'
          dumpPayloadToConsole: false
          dumpPayloadToFile: false
          replaceFile: true
          getParentsAndChildren: false

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'development'
          publishLocation: 'Container'