# Flutter build
variables:
  projectDirectory: 'BudgetTracker-Mobile'

trigger:
- master

jobs:
  - job: Notes
    pool:
      vmImage: 'windows-latest'
    steps:
    - task: GenerateReleaseNotes@3
      inputs:
        outputfile: '$(Build.ArtifactStagingDirectory)\releasenotes.md'
        templateLocation: 'InLine'
        inlinetemplate: |
          <h1>Release notes for build $defname</h1>  
          <b>Build Number</b>  : $($build.buildnumber)    <br>  
          <b>Build started</b> : $("{0:dd/MM/yy HH:mm:ss}" -f [datetime]$build.startTime)     <br>  
          <b>Source Branch</b> : $($build.sourceBranch)  <br>  
          
          # Global list of CS ({{commits.length}})
          {{#forEach commits}}
          {{#if isFirst}}### Associated commits{{/if}}
          * ** ID{{this.id}}** 
             -  **Message:** {{this.message}}
             -  **Commited by:** {{this.author.displayName}} 
             -  **FileCount:** {{this.changes.length}} 
          {{#forEach this.changes}}
                -  **File path (TFVC or TfsGit):** {{this.item.path}}  
                -  **File filename (GitHub):** {{this.filename}}  
          {{/forEach}}
          {{/forEach}}
        generateForOnlyPrimary: false
        generateForOnlyTriggerArtifact: false
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'development'
        publishLocation: 'Container'

  - job: Android
    timeoutInMinutes: 10
    pool:
      vmImage: 'macOS-latest'
    steps:
    # - task: FlutterInstall@0
    #   inputs:
    #     channel: 'stable'
    #     version: 'latest'
    
    # - task: FlutterBuild@0
    #   inputs:
    #     target: 'apk'
    #     projectDirectory: '.'
    #     buildNumber: '$(Build.BuildID)'

    # - task: AndroidSigning@3
    #   displayName: 'Signing and aligning APK file(s) **/*.apk'
    #   inputs:
    #     apkFiles: '**/*.apk'
    #     apksignerKeystoreFile: 'budgettrackerandroidkye'
    #     apksignerKeystorePassword: 'mybudgettrackerpass'
    #     apksignerKeystoreAlias: 'budgettracker'
    #     apksignerKeyPassword: '$(androidkeypass)'
    
    - task: CopyFiles@2
      inputs:
        contents: '**/*.apk'
        targetFolder: '$(build.artifactStagingDirectory)'
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'development'
        publishLocation: 'Container'