# Flutter build
variables:
  projectDirectory: 'BudgetTracker-Mobile'

trigger:
- master

jobs:
  - job: Android
    timeoutInMinutes: 10
    pool:
      vmImage: 'macOS-latest'
    steps:

      - task: CopyFiles@2
        inputs:
          contents: '**/*.apk'
          targetFolder: '$(build.artifactStagingDirectory)'

      - task: XplatGenerateReleaseNotes@3
        inputs:
          outputfile: '$(build.artifactStagingDirectory)/releasenotes.md'
          templateLocation: 'InLine'
          inlinetemplate: |
            **Build Number**: {{Build.BuildNumber}}
            **Build Reason**: {{Build.Reason}}
            **SourceBranch**: {{Build.SourceBranch}}
            **Commit**: {{Build.SourceVersion}}

            {{#if compareReleaseDetails.name}}
            **Compared Release Number**  : {{compareReleaseDetails.name}}    
            {{/if}}

            {{#if {{lookup buildDetails.triggerInfo 'pr.number'}}}}
            **Build Trigger PR Number**: {{lookup buildDetails.triggerInfo 'pr.number'}} 
            {{/if}}

            {{#if pullRequests.length}}
            # Associated Pull Requests ({{pullRequests.length}})
            {{#forEach pullRequests}}
            {{#if isFirst}}### Associated Pull Requests (only shown if  PR) {{/if}}
            *  **{{this.pullRequestId}}** {{this.title}}
            {{/forEach}}
            {{/if}}

            {{#forEach commits}}
            {{#if isFirst}}### Associated commits{{/if}}
            * ** ID{{this.id}}** 
               -  **Message:** {{this.message}}
               -  **Commited by:** {{this.author.displayName}} 
               -  **FileCount:** {{this.changes.length}} 
            {{#forEach this.changes}}
                {{#if this.item.path}} -  **File path (TFVC or TfsGit):** {{this.item.path}} {{/if}}     
                {{#if this.item.path}} -  **File filename (GitHub):** {{this.filename}}  {{/if}}
            {{/forEach}}
            {{/forEach}}
            
          gitHubPat: '$(gitpattoken)'
          dumpPayloadToConsole: false
          dumpPayloadToFile: false
          replaceFile: false
          appendToFile: true
          getParentsAndChildren: false

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'development'
          publishLocation: 'Container'