# Flutter build
variables:
  projectDirectory: 'BudgetTracker-Mobile'

trigger:
- master

jobs:
  - job: Android
    timeoutInMinutes: 10
    pool:
      vmImage: 'macOS-latest'
    steps:

      - task: CopyFiles@2
        inputs:
          contents: '**/*.apk'
          targetFolder: '$(build.artifactStagingDirectory)'

      - task: XplatGenerateReleaseNotes@3
        inputs:
          outputfile: '$(Build.ArtifactStagingDirectory)\releasenotes.md'
          templateLocation: 'InLine'
          inlinetemplate: |
            # Notes for build 
            **Build Number**: {{buildDetails.id}}
            **Build Trigger PR Number**: {{lookup buildDetails.triggerInfo 'pr.number'}} 
            
            # Associated Pull Requests ({{pullRequests.length}})
            {{#forEach pullRequests}}
            {{#if isFirst}}### Associated Pull Requests (only shown if  PR) {{/if}}
            *  **{{this.pullRequestId}}** {{this.title}}
            {{/forEach}}
            
            # Global list of WI ({{workItems.length}})
            {{#forEach workItems}}
            {{#if isFirst}}## Associated Work Items (only shown if  WI) {{/if}}
            *  **{{this.id}}**  {{lookup this.fields 'System.Title'}}
              - **WIT** {{lookup this.fields 'System.WorkItemType'}} 
              - **Tags** {{lookup this.fields 'System.Tags'}}
              - **Assigned** {{#with (lookup this.fields 'System.AssignedTo')}} {{displayName}} {{/with}}
            {{/forEach}}
            
            # Global list of CS ({{commits.length}})
            {{#forEach commits}}
            {{#if isFirst}}### Associated commits  (only shown if CS) {{/if}}
            * ** ID{{this.id}}** 
              -  **Message:** {{this.message}}
              -  **Commited by:** {{this.author.displayName}} 
            {{/forEach}}
          gitHubPat: '$(gitpattoken)'
          dumpPayloadToConsole: false
          dumpPayloadToFile: false
          replaceFile: true
          getParentsAndChildren: false

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'development'
          publishLocation: 'Container'