# Flutter build
variables:
- group: my-variable-group
- name: build-number
  value: '$(Date:yyyyMMdd)'


trigger:
- master

name: $(Date:yyyyMMdd)$(BuildID)
jobs:
  - job: Android
    pool:
      vmImage: 'macOS-latest'
    steps:
    - script: echo $(Build.BuildNumber)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
            echo "##vso[task.setvariable variable=testvar;]testvalue" 

      # - task: CopyFiles@2
      #   inputs:
      #     contents: '**/*.apk'
      #     targetFolder: '$(build.artifactStagingDirectory)'

    - script: echo $(Build.BuildNumber)
    - script: echo $(Build.BuildNumber)

      # - task: XplatGenerateReleaseNotes@3
      #   inputs:
      #     outputfile: '$(build.artifactStagingDirectory)/releasenotes.md'
      #     templateLocation: 'InLine'
      #     inlinetemplate: |
      #       #### source branch:  $(SourceBranchName)
      #       #### Commit:{{buildDetails.sourceVersion}}
      #       #### Branch: {{buildDetails.sourceBranch}}
      #       {{#forEach commits}}
      #       {{#if isFirst}}### Release Notes:{{/if}}
      #       * {{this.message}}
      #       {{/forEach}}
      #     gitHubPat: '$(gitpattoken)'
      #     dumpPayloadToConsole: false
      #     dumpPayloadToFile: false
      #     replaceFile: true
      #     getParentsAndChildren: false

      # - task: PublishBuildArtifacts@1
      #   inputs:
      #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      #     ArtifactName: 'development'
      #     publishLocation: 'Container'