# Flutter build
variables:
  projectDirectory: 'BudgetTracker-Mobile'

trigger:
- master

jobs:
  - job: Android
    timeoutInMinutes: 10
    pool:
      vmImage: 'macOS-latest'
    steps:

      - task: CopyFiles@2
        inputs:
          contents: '**/*.apk'
          targetFolder: '$(build.artifactStagingDirectory)'

      - task: XplatGenerateReleaseNotes@3
        inputs:
          outputfile: '$(build.artifactStagingDirectory)/releasenotes.md'
          templateLocation: 'InLine'
          inlinetemplate: |
            **Build Number**: {{json buildDetails}}
            **Build Reason**: {{Build.Reason}}
            **SourceBranch**: {{Build.SourceBranch}}
            **Compared Release Number**  : {{compareReleaseDetails.name}}    
            **Commit**: {{Build.SourceVersion}}
            
            {{#if compareReleaseDetails.name}}
            **Compared Release Number**  : {{compareReleaseDetails.name}}    
            {{/if}}
            
            {{#forEach commits}}
            {{#if isFirst}}### Associated commits{{/if}}
            ** {{this.id}}** 
               -  **Message:** {{this.message}}
               -  **Commited by:** {{this.author.displayName}} 
               -  **FileCount:** {{this.changes.length}} 
            {{#forEach this.changes}}
                -  **File filename (GitHub):** {{this.filename}}
            {{/forEach}}
            {{/forEach}}
          checkStage: true
          gitHubPat: '$(gitpattoken)'
          dumpPayloadToConsole: false
          dumpPayloadToFile: false
          replaceFile: false
          appendToFile: true
          getParentsAndChildren: false

      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'development'
          publishLocation: 'Container'